#spring.data.mongodb.uri=mongodb://10.0.1.118:27017/max-live-db?authSource=admin

spring.data.mongodb.uri=mongodb://44.209.31.1:27017/max-live-db?authSource=admin
firebase.path=/liveRoom

agora.app.id=0f27c7a324a04bf3be618afe43a4322d
agora.app.certificate=47c61e58b3f84323ac6bce5d3738d567

firebase.credentials.file=max-live-f1bd8-firebase-dev.json
firebase.database.url=https://max-live-f1bd8-default-rtdb.firebaseio.com/
