#spring.profiles.active=local
#
spring.application.name=max-live-spring-home
server.port=8071


spring.data.mongodb.uri=mongodb://10.0.1.118:27017/max-live-db?authSource=admin


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=5

keystore.instance=jks
keystore.classpath=client-keystore.jks
keystore.password=client@1234
gateway.timeout.in.ms=65000

server.error.include-message=always

logging.level.root=INFO


spring.jackson.default-property-inclusion = NON_NULL
#
#logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]
#logging.include-application-name=false
#
#management.zipkin.tracing.endpoint=http://your-zipkin-server-url:9411
#management.tracing.sampling.probability=1.0
#management.tracing.propagation.type=b3
#
#
#management.endpoints.web.exposure.include=health,info,metrics,env,prometheus
#management.prometheus.metrics.export.enabled=true
#management.metrics.distribution.percentiles-histogram.http.server.requests=true
#management.metrics.distribution.percentiles-histogram.http.client.requests=true
#management.observations.key-values.application-name=${spring.application.name}
#management.endpoints.web.exposure.include=*
firebase.path=/liveRoom

agora.app.id=0f27c7a324a04bf3be618afe43a4322d
agora.app.certificate=47c61e58b3f84323ac6bce5d3738d567