#spring.profiles.active=dev
spring.profiles.active=local

spring.application.name=max-live-spring-home
server.port=8071

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=5

keystore.instance=jks
keystore.classpath=client-keystore.jks
keystore.password=client@1234
gateway.timeout.in.ms=65000

server.error.include-message=always

logging.level.root=INFO


spring.jackson.default-property-inclusion = NON_NULL