
spring.data.mongodb.uri=mongodb://10.0.1.118:27017/max-live-db?authSource=admin
#spring.data.mongodb.uri=mongodb://44.209.31.1:27017/max-live-db?authSource=admin
firebase.path=/liveRoom

agora.app.id=3f0ad73cdfcd4092a74604e659f064e2
agora.app.certificate=1a93d6f6047f493597cb21cdfc81f00a

firebase.credentials.file=max-live-f1bd8-firebase-dev.json
firebase.database.url=https://max-live-f1bd8-default-rtdb.firebaseio.com/

