spring.application.name=max-live-spring-home
server.port=8071


spring.data.mongodb.uri=mongodb://10.0.1.194:27017/max-live-db?authSource=admin


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=5

keystore.instance=jks
keystore.classpath=client-keystore.jks
keystore.password=client@1234
gateway.timeout.in.ms=65000

server.error.include-message=always

logging.level.root=INFO


spring.jackson.default-property-inclusion = NON_NULL

firebase.path=/liveRoom

agora.app.id=8fe376695c5a43cdbd2c7aa2441e2160
agora.app.certificate=70315fa22f7649a0babbec69d87210a0

firebase.credentials.file=max-live-1b02e-firebase-adminsdk-mhscw-2609c6ffbe.json
firebase.database.url=https://max-live-1b02e-default-rtdb.europe-west1.firebasedatabase.app/
