spring.application.name=max-live-spring-home
server.port=8071


spring.data.mongodb.uri=mongodb://localhost:27017/max-live-db?authSource=admin&replicaSet=rs0


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=5

keystore.instance=jks
keystore.classpath=client-keystore.jks
keystore.password=client@1234
gateway.timeout.in.ms=65000

server.error.include-message=always

logging.level.root=INFO


spring.jackson.default-property-inclusion = NON_NULL

firebase.path=/liveRoom

agora.app.id=0f27c7a324a04bf3be618afe43a4322d
agora.app.certificate=47c61e58b3f84323ac6bce5d3738d567

firebase.credentials.file=max-live-f1bd8-firebase-dev.json
firebase.database.url=https://max-live-f1bd8-default-rtdb.firebaseio.com/