spring.data.mongodb.uri=mongodb://10.10.10.25:27017/a-live-db?authSource=admin
#spring.data.mongodb.uri=mongodb://103.209.43.28:27017/a-live-db?authSource=admin

firebase.path=/liveRoom

agora.app.id=aba111d3b9564ad289774a44c6c7ea46
agora.app.certificate=0b18da4538894ea08081a5bb1b9e28f5

firebase.credentials.file=a-live-dev-firebase-admin-sdk.json
firebase.database.url=https://a-live-dev-8d25e-default-rtdb.firebaseio.com/

# Liveness monitoring configuration
liveroom.liveness.timeout.minutes=5
liveroom.liveness.scheduler.interval.minutes=3

# Toggle to enable/disable the scheduled liveness checker
liveroom.liveness.scheduler.enabled=true

